### ISSUE TITLE
PAL-A region

### ISSUE THREAD

**Issue by darth3pio** [xlenore/psx-covers#13]
Where a cover shares the same release id between Australia/New Zealand and Europe, is there a preference for EU over ANZ? Or does it just matter that it is a higher quality submission? Given this is your repository I figured I should check before submitting a pull request.

Same question for ps2-covers.

It's largely the same cover just with a localised content rating board logo.

**Comment by xlenore** [comment]
I prefer to prioritize the covers in English, but if another language has better quality, then the cover with the best quality will be used

When I have time I will write some rules to contribute
