### ISSUE TITLE
Wrong cover.

### ISSUE THREAD

**Issue by catchyzin** [xlenore/psx-covers#32]
SCUS-94426 CTR crash team racing, the letters CTR on the title has different colors from the original cover like the image below.
![ps1_crashteamracing_front_thumb](https://github.com/xlenore/psx-covers/assets/143895233/3ba23bbf-9a78-43d5-a393-bb3aa6537c54)

**Comment by Zorklis** [comment]
![Crash_Team_Racing_1999_Sony_US_SCUS-94426_0000](https://github.com/xlenore/psx-covers/assets/85455465/2fb0f2c3-7cbf-4cfb-9805-d6d7ebc91994)
Basically this would be the right one, right? 
Probably a better quality one could be found

**Comment by catchyzin** [comment]
yes.
