### ISSUE TITLE
[SLPS-00829] RIOT STARS - Corrupted cover

### ISSUE THREAD

**Issue by Zoukambada** [xlenore/psx-covers#34]
Fixed cover in 1:1 ratio below:

![SLPS-00829](https://github.com/xlenore/psx-covers/assets/8125662/9350179f-874d-44da-8099-2852d7480ed5)

**Comment by Zorklis** [comment]
Can confirm that the current [SLPS-00829](https://github.com/xlenore/psx-covers/blob/main/covers/SLPS-00829.jpg) is glitched. Looks liek this if downloaded
![SLPS-00829](https://github.com/xlenore/psx-covers/assets/85455465/1d94c930-6ea6-49c9-825d-da26f53ace07)
