### ISSUE TITLE
16 Tales - 1, 2, 3, 4 low resolution covers

### ISSUE THREAD

**Issue by Zoukambada** [xlenore/psx-covers#37]
I recreated the same covers from scratch to get a better resolution image (as the ones here are low and looks custom).

Here it is if you want to add to your collection.

![LSP-99012101](https://github.com/xlenore/psx-covers/assets/8125662/ed7a23ab-3912-4506-a06a-6f704d22d171)
![LSP-99012201](https://github.com/xlenore/psx-covers/assets/8125662/6fcdf748-c31e-4796-b935-a0159fa430e1)
![LSP-99012301](https://github.com/xlenore/psx-covers/assets/8125662/d29ad5e8-df75-413c-bb37-626d8b791958)
![LSP-99012401](https://github.com/xlenore/psx-covers/assets/8125662/c9d32e01-45dc-4082-8d8d-d245b5019d4e)

**Comment by xlenore** [comment]
Thanks it looks great!
