### ISSUE TITLE
[Feature request] Suggestion adition of 3D covers

### ISSUE THREAD

**Issue by andercard0** [xlenore/psx-covers#39]
Hi.

I'd like to contribute with my own 3D covers set for the project. 
There are total of **2.228** covers 67.8Mb in total unziped

Here are some examples: 
![CRASH BANDICOOT_1](https://github.com/xlenore/psx-covers/assets/43047877/921b7a02-2eac-4725-a4f7-4da6d7fa5b49)
![FINAL FANTASY IX  (DISC 1)](https://github.com/xlenore/psx-covers/assets/43047877/04e55b87-6f6e-4f8c-bcd8-9c9add52f668)

**Problem:** 
How do I Pull request it into the project ?
Asking this because you if you notice the covers are only named as follows: **SaGa Frontier 2 (USA).png** there are not code to proper apply it automatically in Duckstation with your tool.

Also, once we found a good way to implement this, I'm inclined to do the same for PCSX2 as well, but, there the set is Huge tho.

I forgot your nick name in Duckstation discord that is why i did not ping you there before lol

**Comment by xlenore** [comment]
Looks great.
Maybe we can add a folder called **"3dcovers"** and when the coverdownloader runs ask the user which one they want to download.

My discord is: xLenore

**Comment by andercard0** [comment]
As per the latest update I've seen the feature has been implemented I consider this issue as done.
Thus I'm closing it, thanks for your work mate!
