### ISSUE TITLE
Not found: Crash Bandicoot - Warped (SCUS-94244)

### ISSUE THREAD

**Issue by Jupiee** [xlenore/psx-covers#41]

**Comment by xlenore** [comment]
The url for the covers was updated
https://github.com/xlenore/psx-covers/blob/main/covers/default/SCUS-94244.jpg


Use this URL https://raw.githubusercontent.com/xlenore/psx-covers/main/covers/${serial}.jpg for default covers, or use https://raw.githubusercontent.com/xlenore/psx-covers/main/covers/3d/${serial}.png for 3D covers.
